//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string Dealership_Adress { get; set; }
        public string Work_Telephone { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
